### ISSUE TITLE
Nan output with zeroed trace

### ISSUE THREAD

**Issue by juliarose-coffey** [uafgeotools/lts_array#16]
If zeroed trace is passed into lts_array/ltsva.py, mdccm calculation produces an array of nan values. This issue is fixed when using np.nanmedian instead of np.median on line #117.

https://github.com/uafgeotools/lts_array/blob/1bcb68033eed879b0d5a6276b87673697138acae/lts_array/ltsva.py#L117

**Comment by davidfee5** [comment]
Agreed with this proposed change. I thought this was already the case in fact. @jwbishop should we start a pull request?

**Comment by jwbishop** [comment]
> If zeroed trace is passed into lts_array/ltsva.py, mdccm calculation produces an array of nan values. This issue is fixed when using np.nanmedian instead of np.median on line #117.
> 
> https://github.com/uafgeotools/lts_array/blob/1bcb68033eed879b0d5a6276b87673697138acae/lts_array/ltsva.py#L117

Great catch! I'll make the change.

**Comment by jwbishop** [comment]
It appears that this bug was introduced in the process of combining the research codes into a Github package.
