### ISSUE TITLE
Error when using data from 3 element array

### ISSUE THREAD

**Issue by olamb245** [uafgeotools/lts_array#19]
I get the following error message when I use data from a 3-element array: `Bad assumption, n ! > 2p`

The error message seems to come from line 79 in 'fast_lts_array'. I'm currently running 'ltsva' with Alpha=1, so it's running with ordinary least squares, not least-trimmed squares. I would understand needing the above error message if you're running least-trimmed with only 3 stations, but I'm not sure why it's needed for ordinary least squares when 3 stations should theoretically work (as far as I understand)?

**Comment by davidfee5** [comment]
I just encountered this as well. We'll make sure it is fixed in an upcoming release. Assuming you worked around this already but you can just modify that line to be `if n <= 2*p and alpha<1.0:`

**Comment by olamb245** [comment]
Yes, I think I came up with a fix very similar to this. Thanks.

**Comment by jwbishop** [comment]
Fixed by #23
