### ISSUE TITLE
int() is used without rounding first

### ISSUE THREAD

**Issue by liamtoney** [uafgeotools/lts_array#20]
The Python [`int()`](https://docs.python.org/3/library/functions.html#int) command **truncates** values. So, e.g., the following occurs:
```python
>> int(1.9)
1
```
this is relevant to _lts_array_ e.g. in this line: https://github.com/uafgeotools/lts_array/blob/4f85442a1d4e821fb5e6bcf45e5a649e8db8f56f/lts_array/ltsva.py#L55

For `fs = 20` Hz, `winlen = 10` s, and `winover = 0.9`, `sampinc` is calculated as 19 samples — **but it should be 20**. This then bleeds into the output time vector, `t`, for this example causing its sampling interval to be 0.95 s rather than 1 s as expected. This causes large timing errors for long array processing routines if users naively calculate a 1 s sampling rate (as I did!).

Changing to
```python
sampinc = int(round((1 - winover) * winlensamp))
```
fixes the above issue. There may be other examples as well.

**Comment by jwbishop** [comment]
Fixed by #23
