### ISSUE TITLE
Deprecation of numpy.asscalar()

### ISSUE THREAD

**Issue by olamb245** [uafgeotools/lts_array#22]
I just installed lts_array on a new machine and found there was an issue with the use of `numpy.asscalar()`, which is now deprecated. Numpy suggests changing to `numpy.ndarray.item()`. The lines affected are:

- 289 in _fast_lts_array.py_
- 283, 389, & 657 in _flts_helper_array.py_

I modified the code on my machine to the above suggestion and lts_array seems to work fine now.

**Comment by jwbishop** [comment]
Thanks for pointing this out Oliver!

This bug (due to a `numpy` update) will be fixed in our next release.

**Comment by jwbishop** [comment]
Fixed by #23
