### ISSUE TITLE
Installation fails due to out-of-date setup.py

### ISSUE THREAD

**Issue by liamtoney** [uafgeotools/lts_array#26]
pip gives the following error when I try to install via `pip install git+https://github.com/uafgeotools/lts_array.git`
```
      running build_scripts
      creating build/scripts-3.10
      error: [Errno 2] No such file or directory: 'Example_Processing.py'
```
It looks like the `scripts` list in [`setup.py`](https://github.com/uafgeotools/lts_array/blob/master/setup.py) is out of date since `Example_Processing.py` does not exist.

**Comment by jwbishop** [comment]
Fixed by #28.
