### ISSUE TITLE
RTD documentation out of date

### ISSUE THREAD

**Issue by liamtoney** [uafgeotools/lts_array#27]
It looks like the RTD docs are built off of 4f85442a1d4e821fb5e6bcf45e5a649e8db8f56f:
> © Copyright Jordan W. Bishop, David Fee, and Curt Szuberla Revision 4f85442a.

Do the RTD build logs show any updates?

**Comment by jwbishop** [comment]
Thanks @liamtoney! The package build on RTD was broken due to the `setup.py` issue logged as #26. This issue was also fixed by #28.
