### ISSUE TITLE
Don't show element # subplot for alpha=1.0

### ISSUE THREAD

**Issue by davidfee5** [uafgeotools/lts_array#5]
The element # subplot should not be shown when alpha=1.0, as it is just a blank plot since no elements are flagged. Alpha=1.0 is just ordinary least squares. This is similar behavior to the array_processing repository default.

**Comment by jwbishop** [comment]
I'm going to re-write the plotting script to be more like the one in `array_processing`.

**Comment by jwbishop** [comment]
Fixed by #7 .
